DESCRIPTION
R/connect.R
R/deploy.R
R/utils.R
tests/testthat/test-print-output.txt
tests/testthat/test-print.R

Create cleaner print methods for R6 classes
Close #8 
Some open questions:
- is this testing idea insane? I like that you can easily preview example output, as well as test that it is somewhat consistent with reality and track changes
- I went ahead and printed the `Content` and `Bundle` objects in a "executable" way, e.g.: `content_item(client, guid = "content-guid")` or `bundle_path("/test/path")`. I thought this would be desirable, since these are usually useful in other contexts and hard to retrieve otherwise. 
- Thoughts on how to present the `client` object in this format? I could obviously do so... but it requires putting the API key into the print method, which is undesirable... I could always mirror the masking that RStudio Connect does...? Or try to figure out / "remember" …

New print methods

---

R/connect.R
R/page.R

This PR would modify the two pagination while loops (one in the `get_apps` R6 method and the other in the `page_cursor` function. 
It does some number checks to see if the current iteration of the while loop would cause the output to exceed the requested limit and modifies the limit to restrict the final query to be only the length of the needed remaining values. 
For example, if a user queries the content on a connect system in the current implementation:
```
library(connectapi)
client <- connect()
client$get_apps(.limit = 30, page_size = 25)
```
Then the result will be of length 50 (or however many apps they have if it is between 25 and 50) rather than the limit requested of 30. 
The new implementation will check that the current length of the output `all` subtracted from the requested …

Pagination

---

DESCRIPTION
NEWS.md
R/parse.R
R/remote.R
man/users_create_remote.Rd
tests/integrated/test-ldap.R
tests/testthat/test-parse.R

Close #135 
We retain much of the "magic" of creating multiple users simultaneously, and do not completely finish #156. However, we started that direction with an adhoc test script.
We also fix a bug in `parse.R` that did not handle length > 1 logical vectors (i.e. NA) properly and add test cases to catch this sort of thing in the future.

Refactor users_create_remote to be safer

---

R/remote.R

Better to construct the glue input separately for a complicated expression with lots of delimiters to avoid this issue.
Fixes https://github.com/r-lib/lintr/issues/1459

fix typo in message glue string

---

tests/testthat/test-deploy.R

The recycling error now comes from vctrs so has a different class. I made the minimum change here, but testing the specific error class is a little brittle, so I'd suggest changing to snapshot tests at some point in the future.

Fix for dev purrr

---

DESCRIPTION

I scraped CRAN to find companies that fund R packages, and noticed that Posit is credited 6 different ways (9 if you include RStudio/RStudio PBC/RStudio, PBC). I'm submitting PRs with the official "Posit Software, PBC" name on the few Posit/PBC varieties to nip it in the bud.

Standardize Posit name

---

R/content.R
R/get.R
man/Content.Rd
man/PositConnect.Rd
man/get_audit_logs.Rd
man/get_content.Rd
man/get_content_old.Rd
man/get_group_members.Rd
man/get_groups.Rd
man/get_procs.Rd
man/get_usage_shiny.Rd
man/get_usage_static.Rd
man/get_users.Rd

CRAN is currently reporting these warnings and they have caused PR tests to fail.
https://cran.r-project.org/web/checks/check_results_connectapi.html

re-document and fix warnings

---

R/content.R

I could reproduce this locally running `pkgdown::build_site_github_pages()` as in CI, but stepping through the code that errors outside of pkgdown, it seemed ok. Regardless, this change seems logically correct, and it will prevent `NA` from being somewhere where `TRUE` or `FALSE` is required, as was the error.

Fix pkgdown vignette rendering

---

R/content.R

Fix error message in content_ensure()

---

tests/integrated/setup.R
tests/integrated/test-connect.R
tests/integrated/test-content.R
tests/integrated/test-deploy.R
tests/integrated/test-deployment.R
tests/integrated/test-get.R
tests/integrated/test-git.R
tests/integrated/test-groups.R
tests/integrated/test-lazy.R
tests/integrated/test-misc.R
tests/integrated/test-tags.R
tests/integrated/test-users.R
tests/integrated/test-zzaudit.R
tests/test-integrated.R

Only one test actually needs a second server, so conditionally skip that test if there's only one server running. 
Fixes #254

refactor: allow integration tests to run with only one server

---

NEWS.md
R/parse.R
R/schedule.R
tests/testthat/test-parse.R

Fixes #259. `as.POSIXct()` doesn't just handle ISO-8601 timestamps correctly.

fix: coerce_datetime loses time part

---

R/connect.R
R/content.R
R/deploy.R
R/page.R
R/utils-ci.R
R/utils.R
R/variant.R
man/Content.Rd
man/PositConnect.Rd
tests/integrated/test-deploy.R
tests/testthat/test-connect.R
tests/testthat/test-content.R

* Eliminates `GET_URL()`, `GET_RESULT()`, and `GET_RESULT_URL()`, they all go through `GET` now.
* All VERB functions now go through a common request/response path and have the option of returning the `httr_response` object or parsing the response body.
* All VERB functions can also take any URL and not just one relative to the API root
* Eliminates the `.empty_object` argument and handling from `PUT`/`PATCH`/`POST`, which was only used in one place and was buggy in general (experienced working on a cookbook recipe)
* Adds tests for the custom `httr_content()` method, previously not covered.
* Adds mock tests for the environment variable endpoints

refactor: consolidate HTTP request methods

---

.github/workflows/pkgdown.yaml

Last CI run on main failed with this: https://github.com/rstudio/connectapi/actions/runs/9898285975/job/27344733776#step:6:1
`git blame` says this is 3 years old, surely the feature has been released by now.

Remove unnecessary dev dependency from pkgdown.yaml

---

R/variant.R

Apparently I forgot to push this to my last PR. Related to #283

Deprecate get_variant_default

---

renv.lock
renv/.gitignore
renv/activate.R
renv/settings.json

No major changes; just a single commit cherry-picked from #283.

chore: update renv environment and infra

---

.Rbuildignore
DESCRIPTION
cran-comments.md

Just a tiny PR to update the DESCRIPTION to reflect that Neal has made a bunch of contributions and I'm now going to be the person submitting to CRAN. I've read that it's helpful to note changes of maintainer in `cran-comments.md`.

chore: update DESCRIPTION with new authors & maintainer

---

DESCRIPTION
NEWS.md
R/parse.R
man/ContentTask.Rd
man/EnvironmentR6.Rd
man/Vanity.Rd
man/VariantR6.Rd
man/VariantSchedule.Rd
man/VariantTask.Rd
man/connectapi-package.Rd
man/content_render.Rd
man/content_restart.Rd
tests/integrated/test-deploy.R
tests/testthat/test-parse.R

Fixes #290
Fix a bug involving the handling of timestamps from Connect.
Connect sends timestamps in RFC 3339 format. Specifically:
- Timestamps with no UTC offset end in `Z`, e.g. `"2020-01-01T01:02:03Z"`
- Timestamps with an offset end in `±hh:mm`, e.g. `"2023-08-22T15:13:14+01:00"`
Details on the approaches used.
- This PR fixes a bug where we would not parse time stamps with an offset, resulting in NA values. It uses a combination of regular expressions and using different time format specifiers for different incoming time stamps.
- Converts all incoming timestamps to UTC. Previously, we only parsed UTC times at all, but just fixing the time format revealed a bug where we assigned UTC to non-UTC timestamps.
- Fixes a bug in `make_timestamp()`, which creates timestamps for Connect. …

fix: parsing time stamps with time zone offsets containing colons

---

R/get.R

While removing manual `nolint` comments, I ran into this function. 
I can not find the function name anywhere in the repo. So it feels fair to remove it.

chore: Remove unused function

---

NEWS.md
R/get.R
man/ContentTask.Rd
man/EnvironmentR6.Rd
man/Vanity.Rd
man/VariantR6.Rd
man/VariantSchedule.Rd
man/VariantTask.Rd
man/get_groups.Rd
tests/testthat/2024.08.0/__api__/v1/groups-125d47.json
tests/testthat/2024.08.0/__api__/v1/groups-4eaf46.json
tests/testthat/2024.08.0/__api__/v1/groups-deae1f.json
tests/testthat/test-get.R

`get_groups(client, prefix = "prefix")` would fail when the `page_size` required pagination — it would hang forever.
Fixes #319
- This hang occur because the `v1/groups` API only ever returns the first page of results when using `prefix`.
- Whereas `v1/users` returns no results when a subsequent page of a `prefix` request is called, `v1/groups` always returns the first page, which causes `connectapi` to just page eternally.
- So, we just don't call the pagination function when we're using a prefix!
- Updated documentation to clarify behavior of different parameters.

fix: prevent hanging when calling `get_groups` with `prefix` and small `page_size`

---

.github/CONTRIBUTING.md
.github/SUPPORT.md
DESCRIPTION
NEWS.md
README.Rmd
README.md
_pkgdown.yml
tests/integrated/test-git.R
tests/testthat/test-git.R

Related to #352 (does not close)
Outstanding problems

chore: change rstudio/connectapi to posit-dev/connectapi

---

NEWS.md
R/connect.R
R/get.R
R/utils.R
man/connect.Rd
man/connectapi-package.Rd
man/get_oauth_credentials.Rd
tests/testthat/2024.08.0/__api__/v1/oauth/integrations/credentials-a1e6cf-POST.json
tests/testthat/test-connect.R

Add the ability to create a Connect client using content visitor-scoped authentication.
Fixes #362
Added a token argument to the `connect()` function. When passed a token and running on Connect, performs an OAuth credential exchange request to get a visitor API key and returns a client using that API key instead. When an argument is provided to `token` but code is not running on Connect, prints a message and returns a client using the provided API key.
I considered a few tradeoffs:
- The general convention in R is to indicate optional arguments by giving them a default `NULL` value. This implementation breaks with the convention — `token` argument has no default value, and I use `missing()` to tell if it has been provided.
- The default value for missing HTTP headers in R is `NULL`, so …

feat: add support for visitor api key

---

.github/workflows/lint.yaml
.lintr

`lintr` v3.2.0 removed a hard dependency on `cyclocomp`, so the cyclocomp linter is failing. This PR installs that package to the lintr CI workflow, and should fix the problem.

chore: fix linting

---

R/connect.R
R/get.R
R/page.R
man/PositConnect.Rd
man/get_packages.Rd
tests/testthat/test-get.R

Simplify `get_packages()`, removing pagination-related parameters.
Fixes #
- Internally, use a response limit of 100000 items for the endpoint.
- Remove `page_size` and `limit` from the user-facing function `get_packages()`.
- To fix tests that broke, alter the `page_offset()` function to cease iteration when the total number of aggregated items reaches the total number of items that the server will return. (Previously, it would continue to request a new page until the number of new items was 0, but the responses always contain the total number of items to be returned!)

fix: simplify `get_packages()`

---

NEWS.md
R/parse.R
tests/testthat/test-parse.R

#291 fixed a bug in time zone parsing. This simplifies the approach in that PR somewhat, with the end-user benefit of displaying time zones in the local time rather than UTC. No accompanying issue.
Instead of creating a character vector of format strings based on the format of the time zone, we do an additional regex pass on the incoming timestamps. This lets us use a single format string to parse them.
The new substitution means that UTC time stamps are now explicitly given `+0000` offsets, which means that the `tz` used in `as.POSIXct` can be the user's local time zone. Previously, they were parsed treating the trailing `Z` as a literal, which meant that to R, they did not have a time zone, so all time stamps had to be parsed as UTC. (This is hard to explain!)
The comprehensive tests we …

fix: minor improvements to time zone parsing

---

R/connect.R
R/schedule.R
man/PositConnect.Rd
tests/testthat/test-parse.R

Remove the last (unconditional) caller of the unversioned timezones API.
Since timezones won't likely change during the course of an R session (and the only calling of this is for printing progress messages, it seems, so whatever), memoize the timezones data on the connect session object, using the approach of trying the v1 API first. Then remove the two places that were calling the API, one of which was not calling the v1 API.

Cache timezone response and remove other caller of unversioned API

---

R/connect.R
R/content.R
R/schedule.R
R/thumbnail.R
R/utils.R

Add an alias to `unversioned_url()` that we can use for the places where we call an old API but only as a fallback when the new API isn't available on the Connect server. By using this, we can more easily find the places where we unconditionally call undocumented APIs by searching the code for `unversioned_url`, which will help us burn down that list.
Read the code, replace as needed. There is no behavior change.

refactor: add unversioned_fallback_url() alias

---

R/utils-ci.R

Removes the last caller of this unversioned API. Only used in the integration tests.
Switch to `v1/users/guid/keys` where available, falling back to the old one where it doesn't. Some other tidying while in there.
If the integration tests pass, this proves that the fallback works. But until we do #395, we don't have a test run that exercises this. For better or worse, this is test only code.

refactor: use v1 keys API in integration test setup
