posit-dev/connectapi

R/connect.R
R/migrate-hackery.R
tests/testthat/integrated-tests/test-content.R

internal and experimental playground for acls

Add internal exploration

---

R/content.R
tests/testthat/integrated-tests/test-content.R

protect against NULL content titles (i.e. pins)

Fix content title

---

R/deploy.R

Use a relative path in `writeManifest` in order to generate one that works!
Tested locally and this fix works.

attempt to fix static bundle deploys

---

DESCRIPTION
Jenkinsfile
Makefile
R/parse.R
R/ptype.R
tests/testthat/test-parse.R

Fix ptypes

---

DESCRIPTION
R/ptype.R
tests/integrated/test-deploy.R

connect seems to always return UTC
if there is any variance, we will have to make this more configurable
close #77

set timezone to UTC

---

R/tag_page.R
README.Rmd
README.md

Close #11
Related to #15 (does not resolve - we are basically punting for now)
Close #24 (I think this is the main case where Suggests was not protected)

update codecov to use main

---

DESCRIPTION
NEWS.md
R/content.R
R/deploy.R
man/bundle_path.Rd
tests/testthat/examples/rmarkdown_deployer/main.Rmd
tests/testthat/examples/rmarkdown_deployer/manifest.json
tests/testthat/test-deploy.R
tests/testthat/test-print-output.txt

close #18 
close #13 
close #19

clean up some R6 print objects

---

DESCRIPTION
NEWS.md
R/audits.R
R/connect.R
README.Rmd
README.md
tests/integrated/test-connect.R
tests/integrated/test-zzaudit.R
tests/testthat/test-audit.R
tests/testthat/test-connect.R

add integration test for audit_r_versions
a few other little issues and improved testing
close #16

misc changes

---

DESCRIPTION
NEWS.md
R/content.R
R/ptype.R

@dbkegley FYI 😄 
(Have not tested yet. We will see what happens in CI haha)

New bundle api

---

.github/workflows/integration-tests.yaml
.github/workflows/pkgdown.yaml
.github/workflows/test-coverage.yaml
Makefile
R/connectapi.R
R/content.R
README.Rmd
README.md
man/permissions.Rd

- Bump Connect version
- Improve documentation

Miscellaneous improvements

---

DESCRIPTION
NEWS.md
tests/integrated/test-content.R

Bump version to dev and fix broken integration test

Post release

---

R/connect.R

fix_min_data_version

---

.github/workflows/integration-tests.yaml
.github/workflows/pkgdown.yaml
.github/workflows/test-coverage.yaml
Makefile
R/connectapi.R
R/ptype.R
inst/ci/test-connect-lic.yml
inst/ci/test-connect.yml
tests/integrated/_snaps/schedule.md

Bump version of Connect

---

NEWS.md
R/connect.R
R/utils.R
vignettes/customize-http.Rmd

Close https://github.com/rstudio/connectapi/issues/161
Ultimately hard to test in CI because we do not currently have an "SSL Connect with invalid cert" (although that is something that we could potentially add to CI at some point).

Update httr docs

---

DESCRIPTION
NEWS.md
connectapi.Rproj

Increment version number to 0.1.2

---

NEWS.md
R/connect.R
R/deploy.R
man/PositConnect.Rd
man/bundle_dir.Rd
man/bundle_path.Rd
man/bundle_static.Rd
man/deploy.Rd

Replaces https://github.com/rstudio/connectapi/pull/189.

remove experimental bundle use

---

R/connect.R
R/content.R
R/deploy.R
R/schedule.R
R/variant.R
man/Bundle.Rd
man/Content.Rd
man/ContentTask.Rd
man/EnvironmentR6.Rd
man/PositConnect.Rd
man/Task.Rd
man/Vanity.Rd
man/VariantR6.Rd
man/VariantSchedule.Rd
man/VariantTask.Rd

Minimal docs for everything.
Rooted off of https://github.com/rstudio/connectapi/pull/190.
Close #45

roxygen silence

---

NEWS.md
R/connect.R
R/content.R

Content$delete_tag removes that tag from a content item

---

.github/workflows/pkgdown.yaml
_pkgdown.yml

This _might_ be enough. 🤞 
fixes #197

development documentation

---

R/tags.R
man/connectapi-package.Rd
man/tags.Rd

Prune extra <li>

---

.github/workflows/R-CMD-check-HTML5.yaml
.github/workflows/R-CMD-check.yaml
.github/workflows/integration-tests.yaml
.github/workflows/lint.yaml
.github/workflows/pkgdown.yaml
.github/workflows/pr-commands.yaml
.github/workflows/test-coverage.yaml
.gitignore

Some general version bumping, some pulling in the latest from https://github.com/r-lib/actions/tree/v2-branch/examples

Update actions workflows (versions etc.)

---

NEWS.md
R/parse.R
tests/testthat/test-parse.R

Rebased #192 and pushed to rstudio/connectapi so that the integration tests can run

Fix type conversion in job logs

---

.github/ISSUE_TEMPLATE/issue_template.md
.github/SUPPORT.md
README.Rmd
README.md

Update forum URL

---

.github/CONTRIBUTING.md

Update CONTRIBUTING.md with accurate instructions for integration tests

---

DESCRIPTION
NEWS.md
cran-comments.md
man/ContentTask.Rd
man/EnvironmentR6.Rd
man/Vanity.Rd
man/VariantR6.Rd
man/VariantSchedule.Rd
man/VariantTask.Rd
man/connectapi-package.Rd

Release 0.4.0.
Addresses #324 
Currently in CRAN.

release: 0.4.0

---

.Rbuildignore
.gitignore
DESCRIPTION
NEWS.md

Move to dev version number; add some editor files to `.Rbuildignore`; add test license at the top level to `.gitignore` and `.Rbuildignore`.

chore: update to dev version

---

.gitignore

Add a `/inst/scratch` directory to `.gitignore` so I have a place to save scratch files that won't accidentally get tracked.

chore: give myself a scratch dir

---

DESCRIPTION
NEWS.md

chore: increment version number to 0.5.0.9000

---

DESCRIPTION
NEWS.md
README.md
renv.lock
renv/activate.R

chore: release 0.6.0

---

DESCRIPTION
NEWS.md
renv.lock

chore: release connectapi 0.7.0

---

DESCRIPTION
NEWS.md

chore: increment version number to 0.7.0.9000
